travis:
  secure:
    BINSTAR_TOKEN: Ltvqs4RE81UY1IfPKBG4GY4CdtSwrq7zK7aCcJB6RZtLHOKoU5YNokycriiH77eoT2dwNVUWPp9vsB8H5QmT4UJWjcwwgCgqOunluoLg5S67XyTBr1cqevLumngxAAZZZslrSsp5sp+hCi7GUvCJCmCCI+fW4w3i1JQKp8XkFLr4+YP1si2ytQm92FXStqdZMo2N+wDTdBdO8k3+KfEf6Er8p9LpeBshQw3TXfheTcP7JGz1f0gdw5iq4KDahrP7MbpcPq8UXqoQzeLEsl6hRr2qvidZ9mW7lrL/F6mKGvZshn907ElV/LS1NPkVDYfAn82z8uuVFuDu6XvItYHF0xkrfVA7Sdpdkl5cULqZFYRWvAQcWM3BgrFO6uFczPx6jqpUkCN0QpOXW7s6gtpCEvkj9ae0JJwFbJQ5jLkf4rpk/af/wlIItwDUF+WNnsOeChfdvfZ9aIBpol6cwqwxlLn3LXaTIEU85fYZ51Wo1L90uapHOOjw5Uyk1Y9t1nfkiwZHpTJc3tAdWaIX15cvH09F4+f/KLGz0PoloeQa6tF30sCv4mr6FeEoUmBSGkRp1gGsz7LhKUx2oQj+kSaKUI7apWxANpRsyefnhnjuWFp0oUz1vLoUU7EcvFfGxgLUkP1+wcEVqEdV4O/RagkoYBzoxXf9pWw7Qtc/yK4ktXQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
